### ISSUE TITLE
Pushed At instead of Updated At

### ISSUE THREAD

**Issue by Lergin** [abraham/github-repository#34]
Currently the date field is showing the date the repo was last updated but this might not really be what would make sense there as this date isn't updated everytime there was a commit to the repo but only when something like the description was changed (see: https://stackoverflow.com/questions/15918588/github-api-v3-what-is-the-difference-between-pushed-at-and-updated-at) therefor i think it would be better to use the pushedAt date :)

**Comment by abraham** [comment]
Thanks for the suggestion!
